# Generated by Django 4.2.11 on 2025-11-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('images', models.ImageField(blank=True, null=True, upload_to='')),
                ('views', models.IntegerField(default=0)),
                ('readtext', models.BooleanField(default=False)),
                ('good', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BoardModel',
        ),
    ]
