# Generated by Django 4.2.11 on 2025-11-13 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0002_snsmodel_delete_boardmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snsmodel',
            old_name='readtext',
            new_name='subscribe',
        ),
    ]
